= SoftHalfDuplexSerial Library for Arduino =

 This library implement all the required operation to drive Dynamixel servo,
 using only one wire.
 It required the halfDuplexSerial lib (SoftHalfDuplexSerial.cpp & .h)
 Limitations:
  - The pin should support change interrupts (see halfDuplexSerial lib)
  - Baudrate is limited (57 600bps ~ 115 200bps for 16Mhz Arduino board)
  - 5V Arduino Board (I didn't try with 3.3V board as I didn't have one)

You can customize servo control by editing the DynamixelArduinoConfig.h file.
The librarie has been written and tested with AX-12 servo, it should work with other Dynamixel servos (including MX TTL series) with some adjustement (Compliance settings are not available in MX series as it is drive by PID gain).

For more information about this library please visit us at
http://

== License ==

Copyright (c) Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
